import type { Metadata } from 'next'
import { Inter as FontSans } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import AuthProvider from '@/components/auth/AuthProvider'
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs'
import { cookies } from 'next/headers'
import { Toaster } from "@/components/ui/toaster"

const fontSans = FontSans({ subsets: ['latin'], variable: "--font-sans" })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export const dynamic = 'force-dynamic'

export default async function RootLayout({ children, }: { children: React.ReactNode }) {
    const supabase = createServerComponentClient({ cookies });

    const { data: { session }, } = await supabase.auth.getSession();
    const accessToken = session?.access_token || null;

    return (
        <html lang="en">
            <body className={cn(
                "font-sans min-h-screen flex flex-col items-center w-full",
                fontSans.variable
            )}>
                <AuthProvider accessToken={accessToken}>
                    {children}
                </AuthProvider>
                <Toaster />
            </body>
        </html>
    )
}
